language: node_js
node_js:
- node
branches:
  only:
  - master
script:
- cd adventure-book
- npm install
- npm test
- cd ..
- sonar-scanner
notifications:
  slack:
    rooms:
      secure: JUftVecr1tHK+n9zdEKqj9owkADUbp9aEcFtlDlG2nhyyb2NvOpWMc9E4Xb8YD21lKVh/DJz8m5K9O2/ixLa+COLOyeIY9UEzgvOMsiC4F0x3xMxM6Z1TqwMMtkmcVWWatXr2JEzUgCxnhWml3/w6pGCdekuGzv+S/AV7Q/IJlCsNnFwEbzXUnY+pyh7CQA1ahmCVof4GtvzZPp7YwxD8l11vKv6p4MxFs0CjMkSN5bzQ601BIuBCVgaI/awQk3QMXUJKmW/czqfDgJCowDzaxjrKs6c8FAGHebOGO2BcQrgGow1k4PUI2A+QEkxAVGfTcfiDmjQMSlaGKpFvKRkNw6yuIBaRWzROUUGiIRG9TEIUkdasMBVlctLBKTmenSbJpHpt1/aCQU6lk6NQTCEIJShZ2psUhPBNcT2leaVku0XzW9Xdcj1Tdiuv43I5kGvgULZs83Kw1of6iT4OfSkZdPm+1k/uu2feTx5h6bD4TTgPtVoN9Bb7kgf9NX5gyD5KtE7HJG//tbdCKUPj2GgUhQtNS1ZuuCASymSXEss3AXkUjdonJHQFuA6vhYbetHnLFbvu0wyT6HW7QyLHIgpv3n+0LbWpeoFJU0FIgcMwaXw41PQDWgwhwTktRZkTNo73YdcDIqY9e/m4QZM0WqXCxrNRBRwOnBaXlOoav46YWY=
    on_success: always
dist: trusty
addons:
  sonarcloud:
    organization: sytw12018
    token:
      secure: u6Yva/bldwlNE3xAl8x0OJmD3FKLyyE6dOO5WiP0NTSdbyb19BdF84+1gMw0QXdL9wREtS0zScCUDDNvJwXMzTYRHubeC5paTX7LvVU3KcnyFmjdFovqawzlWinANid2uzjzD5f7WaIN07sTPTouT7q6/J7LvZylag3MAvqN13tGrb4z4gY/7o65ImWZHm8RxPtCPmog1lFj0ga4CYxNajCoIy1sQfhWjuHAGmpU2m4d9Nxo0eKLSGrnqHy6mVQ4mXSZmxdzmgG7FHEWUEl2kuNgg0SrvFzDVpQZRE14wVVdSCaOQxoBfm9pl5AhVuoXB6p1FJhmMfHRJ2/osx0Ha4cfdTGl30CPBuyeNt2ULW5yQ23h7G7yNuNqWJLkPh/GSjBxzXXPaFOOqK3zf8GSYVArclKNw14G9fQ5gT6dQLCjeIK+p1VC1sMwov0o6MKws0c4Nde7fURCCOje6liZYYvg9nNzawek1z5A4IHzHWc4R/rB8WyT1gVCp/bY35nUawLVLRf33TVWsHsgGWsyVsLFC2rQeU8KaIvuRzS50MU3KwMMdX04Z1ysoEb2dUEXtkVVLmWz1GqzTiFtCvZCNtB04vIcOa25QmILLWGZPGA1mXyK4nSW/cLRYnw7jdNoOTC/ZE4PQcQc5f4TPODah5pEuK3LI3hUzfxqZU783R4=
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_4adc998b3a13_key -iv $encrypted_4adc998b3a13_iv
  -in ULL.conf.enc -out ULL.conf -d
